version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/src

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-store:
